require("chegoryu.plugins-setup")

require("chegoryu.core.colorscheme")
require("chegoryu.core.filetype-options")
require("chegoryu.core.keymaps")
require("chegoryu.core.options")

require("chegoryu.plugins.autopairs")
require("chegoryu.plugins.comment")
require("chegoryu.plugins.gitsigns")
require("chegoryu.plugins.lualine")
require("chegoryu.plugins.nvim-cmp")
require("chegoryu.plugins.nvim-tree")
require("chegoryu.plugins.telescope")
require("chegoryu.plugins.template")
require("chegoryu.plugins.trailing-whitespace")
require("chegoryu.plugins.treesitter")
require("chegoryu.plugins.trim")

require("chegoryu.plugins.lsp.lspconfig")
require("chegoryu.plugins.lsp.lspsaga")
require("chegoryu.plugins.lsp.mason")
require("chegoryu.plugins.lsp.null-ls")
