CompileFlags:
  Add:
  - -DCHEGORYU
  - -Wall
  - -Wextra

Diagnostics:
  ClangTidy:
    Add:
    - bugprone-*
    - performance-implicit-conversion-in-loop
    - readability-identifier-naming
    Remove:
    - bugprone-narrowing-conversions

---
If:
  PathExclude: .*\.c
CompileFlags:
  Add:
  - -std=c++26

---
If:
  PathMatch: .*\.c
CompileFlags:
  Add:
  - -std=c2x
