require("chegoryu.core.filetype-options.common")

require("chegoryu.core.filetype-options.cmake")
require("chegoryu.core.filetype-options.cpp")
require("chegoryu.core.filetype-options.csharp")
require("chegoryu.core.filetype-options.go")
require("chegoryu.core.filetype-options.java")
require("chegoryu.core.filetype-options.kotlin")
require("chegoryu.core.filetype-options.python")
require("chegoryu.core.filetype-options.rust")
require("chegoryu.core.filetype-options.shell")
