name: Bazel CI

on:
  push:
    branches:
      - main
    tags:
      - "**"

jobs:
  test:
    name: Build and test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.9.1
        with:
          bazelisk-cache: true
          disk-cache: true
          repository-cache: true

      - name: Build
        shell: bash
        run: bazel build //...

      - name: Test
        shell: bash
        run: bazel test //...
